config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/team', to: "pages#team", as: :team
  resources :notes

  resources :dashboards do
    resources :transactions, only: [:index, :edit, :update, :new, :create, :destroy]
    get '/charts/values', to: 'charts#values'
    get '/charts/pie', to: 'charts#pie'
    get '/charts/sparkline', to: 'charts#sparkline'
  end
  resources :ressources, only: [:index, :edit, :update]do
    resources :votes
  end
  get '/ressources/exchanges', to: 'ressources#exchanges', as: :exchanges
  get '/ressources/wallets', to: 'ressources#wallets', as: :wallets
  get '/ressources/youtube', to: 'ressources#youtube', as: :youtube
end

app/models/ressource.rb
class Ressource < ApplicationRecord
  has_one_attached :photo
  has_many :votes, dependent: :destroy
end

app/controllers/ressources_controller.rb
class RessourcesController < ApplicationController
  def index
    @ressources = Ressource.where(user_id: current_user)
    @vote = Vote.new
  end

  def exchanges
    @ressources = Ressource.where(category: "Exchange")
    @ressources = @ressources.sort_by{ |ressource| -ressource.votes.length }
    @vote = Vote.new
  end

  def wallets
    @ressources = Ressource.where(category: "Wallet")
    @ressources = @ressources.sort_by{ |ressource| -ressource.votes.length }
    @vote = Vote.new
  end

  def youtube
    @ressources = Ressource.where(category: "Youtube")
    @ressources = @ressources.sort_by{ |ressource| -ressource.votes.length }
    @vote = Vote.new
  end

  private

  def ressource_params
    params.require(:ressource).permit(:name, :description)
  end


end

app/views/ressources/_resources.html.erb
<% @ressources.each do |ressource| %>
  <div class="pilot-card" style="margin: 30px auto">
    <div class="d-inline-flex align-items-center">
      <!--<%= cl_image_tag ressource.photo.key, height: 70, width: 70, crop: :fill %>-->
      <%= link_to cl_image_tag(ressource.photo.key, height: 70, width: 70, crop: :fill), ressource.link, target: "_blank" %>
      <div class="px-4">
        <h3><%= ressource.name %></h3>
        <p><%= ressource.description %></p>
        <% if Vote.where(user_id: current_user.id, ressource_id: ressource.id).length > 0 %>
          <%= link_to "<i style='color:#EABF17' class='fas fa-thumbs-up'></i> Like (#{ressource.votes.length})".html_safe, ressource_vote_path(ressource, Vote.where("user_id = '#{current_user.id}' AND ressource_id = '#{ressource.id}'").first), method: :delete, style:"color: #EABF17; font-weight:bold" %>
        <% else %>
          <%= link_to "<i style='color:#EABF17' class='far fa-thumbs-up'></i> Like (#{ressource.votes.length})".html_safe, ressource_votes_path(ressource), method: :post, style:"color: gray" %>
        <% end %>
      </div>
    </div>
  </div>
<% end%>

app/views/ressources/_ressources-nav.html.erb
<div class="resources-nav">
  <%= link_to 'Exchanges', exchanges_path, id: "exchanges", class:"resources-nav-link" %>
  <%= link_to 'Web Wallets', wallets_path, id: "wallets", class:"resources-nav-link" %>
  <%= link_to 'YouTube', youtube_path, id: "youtube", class:"resources-nav-link" %>
</div>

app/views/ressources/exchanges.html.erb
<div class="py-5"></div>
<div class="container">
  <div>
    <%= render "ressources-nav" %>
    <%= render "resources" %>
  </div>
</div>

app/views/ressources/index.html.erb
<div class="py-5"></div>
<div class="container-ressources" style="min-height: 83vh">
  <div class="main-container">
  <%if @ressources.empty? %>
    <h1 class='py-4'>You don't have any ressource yet</h1>
    <%= link_to '<i class="fas fa-plus"></i>  Add a ressource'.html_safe, new_ressource_path, class: "btn-flat" %>
    <%else %>
    <div class="d-inline-flex align-items-center">
      <h1 class='py-4'>Your ressources</h1>
      <%= link_to '<i class="fas fa-plus"></i> Add a ressource'.html_safe, new_ressource_path, class: "btn-flat ml-4" %>
    </div>
      <% @ressources.each do |ressource| %>
    <div>
      <div class="ressources-card">
        <div class="second-card">
        <%= ressource.name %>
          <div>
          <%= link_to edit_ressource_path(ressource) do%>
          <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to ressource_path(ressource.id), method: :delete, data: {confirm: "Are you sure?"} do%>
          <i class="fas fa-trash"></i>
          <% end %>
          </div>
        </div>
        <div>
        <%= ressource.description %>
        </div>
      </div>
      <% end%>
      <% end%>
  </div>
</div>

app/views/ressources/wallets.html.erb
<div class="py-5"></div>
<div class="container">
  <div>
    <%= render "ressources-nav" %>
    <%= render "resources" %>
  </div>
</div>

app/views/ressources/youtube.html.erb
<div class="py-5"></div>
<div class="container">
  <div>
    <%= render "ressources-nav" %>
    <%= render "resources" %>
  </div>
</div>