config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/team', to: "pages#team", as: :team
  resources :notes

  resources :dashboards do
    resources :transactions, only: [:index, :edit, :update, :new, :create, :destroy]
    get '/charts/values', to: 'charts#values'
    get '/charts/pie', to: 'charts#pie'
    get '/charts/sparkline', to: 'charts#sparkline'
  end
  resources :ressources, only: [:index, :edit, :update]do
    resources :votes
  end
  get '/ressources/exchanges', to: 'ressources#exchanges', as: :exchanges
  get '/ressources/wallets', to: 'ressources#wallets', as: :wallets
  get '/ressources/youtube', to: 'ressources#youtube', as: :youtube
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer footer-bg">
<i class="fab fa-creative-commons"> Crypto pilot 2021 all rights reseved</i>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-discord"></i></a>
  </div>
</div> %>
<div class="footer">
  <p>This project has been developed with <i id="coffee" class="fas fa-mug-hot"></i> by dedicated</p>
  <%= link_to 'Le Wagon students', team_path %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-bg">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_crypto2.png", class:"rounded" , width: "200"; %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="box">
          <div id="home">
            <%= link_to "Home", root_path, class: "navbar-buttons nav-active" %>
          </div>
          <div id="dashboard">
            <%= link_to "Pilots", dashboards_path, class: "navbar-buttons" %>
          </div>
          <div id="journal">
            <%= link_to "Journal", notes_path, class: "navbar-buttons" %>
          </div>
          <div id="ressources">
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
            </button>

            <li class="nav-item dropdown">
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <%= link_to 'Ressources', "#", class: "dropdown-toggle navbar-buttons", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
               <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Exchanges", exchanges_path, class: "dropdown-item" %>
                  <%= link_to "Wallets", wallets_path, class: "dropdown-item" %>
                  <%= link_to "Youtubes", youtube_path, class: "dropdown-item" %>
                </div>
              </div>
            </li>
          </div>
        </div>
        <div class="navbar-buttons">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:'mx-4 btn btn-dark' %>
        </div>
        <div class="navbar-buttons">
          <div class="user-name">
            <p> <%= current_user.username %></p>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Edit profil",  edit_user_registration_path, class: "dropdown-item" %>
                <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
      <% else %>
    </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Sign Up", new_user_registration_path, class: "mx-2 btn btn-flat" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log In", new_user_session_path, class: "mx-2 btn btn-secondary" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>



 <%# <li class="nav-item dropdown"> %>
      <%# <% if current_user.avatar.attached? %>
        <%# <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <%# <% else %>
        <%# <%= image_tag 'user_blank.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
      <%# <% end %>

      <%# </li> %>