config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/team', to: "pages#team", as: :team
  resources :notes

  resources :dashboards do
    resources :transactions, only: [:index, :edit, :update, :new, :create, :destroy]
    get '/charts/values', to: 'charts#values'
    get '/charts/pie', to: 'charts#pie'
    get '/charts/sparkline', to: 'charts#sparkline'
  end
  resources :ressources, only: [:index, :edit, :update]do
    resources :votes
  end
  get '/ressources/exchanges', to: 'ressources#exchanges', as: :exchanges
  get '/ressources/wallets', to: 'ressources#wallets', as: :wallets
  get '/ressources/youtube', to: 'ressources#youtube', as: :youtube
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  serialize :asset
  belongs_to :user
  has_many :transactions, dependent: :destroy
  validates :name, presence: true

  def average_cost_price(asset_id, date)
    asset_total_spent(asset_id) / tokens_bought(asset_id, date)
  end

  def market_price(asset_id, date)
    return PriceHistory.where("id_name = '#{Asset.find(asset_id).id_name}' AND date = ?", date).last.price
  end

  # Permet de cacluler le nombre de token achetés pour un actif depuis le début
  def tokens_bought(asset_id, date)
    transactions = Transaction.where("dashboard_id = #{self.id} AND date <= ?", date)
    asset_transactions = transactions.where("asset_id = #{asset_id}")
    buy_transactions = asset_transactions.where("direction = 'Buy'")
    token_bought = 0
    buy_transactions.each do |transaction|
      token_bought += transaction.quantity
    end
    return token_bought
  end

  # Permet de calculer le montant dépensé dans un asset depuis le début du pilot
  def asset_total_spent(asset_id)
    asset_transactions = @transactions.where("asset_id = #{asset_id}")
    buy_transactions = asset_transactions.where("direction = 'Buy'")
    total_spent = 0
    buy_transactions.each do |transaction|
      total_spent += (transaction.quantity * transaction.price)
    end
    return total_spent
  end

  def compute_buying_sum(buy_transactions)
    buying_sum = 0
    buy_transactions.each do |transaction|
      buying_sum += transaction.quantity
    end
    return buying_sum
  end

  def compute_selling_sum(sell_transactions)
    selling_sum = 0
    sell_transactions.each do |transaction|
      selling_sum += transaction.quantity
    end
    return selling_sum
  end

  # Permet de calculer le nombre de coins actuellement dans le pilot pour chaque asset
  def asset_qty(asset_id, date)
    asset_transactions = @transactions.where("asset_id = #{asset_id} AND date <= ?", date)
    buy_transactions = asset_transactions.where("direction = 'Buy'")
    sell_transactions = asset_transactions.where("direction = 'Sell'")
    buying_sum = compute_buying_sum(buy_transactions)
    selling_sum = compute_selling_sum(sell_transactions)
    return buying_sum - selling_sum
  end

  # Permet de créer la première partie du hash pour ce qu'il y a aujourd'hui dans le pilot
  def create_hash(date)
    assets = {}
    @assets_id_list.each do |asset_id|
      assets[Asset.find(asset_id).id_name] = {
        id: asset_id,
        quantity: asset_qty(asset_id, date),
        total_spent: asset_total_spent(asset_id),
        number_of_transaction: @transactions.where("asset_id = #{asset_id}").length,
        average_cost:
        if tokens_bought(asset_id, date).zero?
          0
        else
          average_cost_price(asset_id, date)
        end,
        market_price: market_price(asset_id, date),
        pnl:
        (market_price(asset_id, date) * asset_qty(asset_id, date)) -
        (average_cost_price(asset_id, date) * asset_qty(asset_id, date)),
        date: date
      }
    end
    return assets
  end

  # Permet de récupérer la liste des id des assets actuellement dans le pilot
  def assets_id_list
    @assets_id_list = []
    transactions = Transaction.where("dashboard_id = #{self.id}")
    transactions.each do |transaction|
      next if @assets_id_list.include?(Asset.find(transaction.asset_id).id)

      @assets_id_list << Asset.find(transaction.asset_id).id
    end
  end

  # Permet de metter à jour la table des historiques des prix par asset et par date
  def update_price_history(asset, json)
    json["prices"].each do |element|
      price = PriceHistory.find_by(date: Time.at(element[0]/1000).to_date, id_name: asset.id_name)
      if price.nil?
        PriceHistory.create(id_name: asset.id_name, date: Time.at(element[0]/1000).to_date, price: element[1], asset_id: asset.id)
      else
        price.update(id_name: asset.id_name, date: Time.at(element[0]/1000).to_date, price: element[1], asset_id: asset.id)
      end
    end
  end

  # Permet d'obtenir l'historique des prix des actifs du wallet
  def get_history(number_of_days)
    vs_currency = "USD"
    assets_id_list # permet de définir @assets_id_list
    @assets_id_list.each do |asset_key|
      asset = Asset.find(asset_key.to_i)
      res_api = URI.open("https://api.coingecko.com/api/v3/coins/#{asset.id_name}/market_chart?vs_currency=#{vs_currency}&days=#{number_of_days}&interval=daily")
      json = JSON.parse(res_api.read)
      json["prices"].delete_at(-2)
      update_price_history(asset, json)
    end
  end

  # Permet de récupérer toutes les dates depuis la première transac à aujourd'hui + le nb de jour que cela représente
  def define_dates(transactions)
    first_date = transactions.first.date
    number_of_days = (Date.today - first_date).to_i + 1
    dates = []
    i = 0
    number_of_days.times do
      dates << (first_date + i)
      i += 1
    end
    return [number_of_days, dates]
  end

  # Permet de créer le hash complet avec les actifs du pilot pour chaque jour depuis le début
  def define_assets
    return [0] if self.transactions == []

    @transactions = self.transactions.order('date ASC')
    dates = define_dates(@transactions)[1]
    get_history(define_dates(@transactions)[0])

    daily_hash = dates.map do |date|
      create_hash(date)
    end
    p daily_hash
    return daily_hash
  end

  # Permet de calculer la valeur total du pilot pour un hash (jour) donné
  def total_value(hash)
    total_value = 0
    keys = hash.keys
    keys.each do |key|
      total_value += hash[key][:quantity] * hash[key][:market_price]
    end
    return total_value
  end

  def charts
    transactions = self.transactions.order('date ASC')
    assets = define_assets
    chart_values = values(transactions, assets)
    return chart_values
  end

  # Permet de générer les données pour le graph
  def values(transactions, assets)
    dates = define_dates(transactions)[1]
    values = dates.map do |date|
      [date, total_value(assets[dates.index(date)])]
    end
    return values
  end

  # Permet de calculer le pourcentage que représente chaque asset dans le pilot pour aujourd'hui
  def percentage(assets)
    assets = positive_assets(assets.last)
    total_value = total_value(assets)
    keys = assets.keys
    keys.each do |key|
      assets[key][:percentage] = (assets[key][:quantity] * assets[key][:market_price]) / total_value * 100
    end
    return assets
  end

  # Permet de générer les valeurs pour le pie chart du pilot (date = aujourd'hui)
  def pie
    assets = define_assets
    assets = percentage(assets)
    keys = assets.keys
    pie_array = keys.map do |key|
      {
        name: key,
        y: assets[key][:percentage].round(2),
        drilldown: key
      }
    end
    return pie_array
  end

  # Permet de calculer la PnL total d'un pilot pour un hash (jour) donné
  def total_pnl(asset_hash)
    keys = asset_hash.keys
    total = 0
    keys.each do |key|
      total += asset_hash[key][:pnl]
    end
    return total
  end

  def sparklines
    keys = define_assets.last.keys
    prices = {}
    keys.each do |key|
      history = PriceHistory.where("id_name = '#{key}'")
      prices[key] = history.map do |value|
        [value.date, value.price.round(2)]
      end
    end
    prices = order_prices(prices)
    return prices
  end

  def order_prices(prices)
    keys = prices.keys
    keys.each do |key|
      prices[key] = prices[key].sort { |a, b| a[0] <=> b[0] }
    end
    return prices
  end

  def positive_assets(assets)
    keys = assets.keys
    positive_assets = {}
    keys.each do |key|
      positive_assets[key] = assets[key] if assets[key][:quantity].positive?
    end
    return positive_assets
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @dashboards = Dashboard.where(user_id: current_user)
  end

  def show
    @dashboard = Dashboard.find(params[:id])
    result = @dashboard.define_assets
    if result == [0]
      @assets = 0
      @total_pnl = 0
    else
      @assets = @dashboard.positive_assets(result.last)
      @total_pnl = @dashboard.total_pnl(@assets)
    end
  end

  def new
    @dashboard = Dashboard.new
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)
    @dashboard.user = current_user
    if @dashboard.save
      redirect_to dashboards_path
    else
      render :new
    end
  end

  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy!
    redirect_to dashboards_path
  end

  def update
    @dashboard = Dashboard.find(params[:id])
    @dashboard.update(name: dashboard_params[:name])
    redirect_to dashboards_path
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:name)
  end
end

app/views/dashboards/edit.html.erb
<div class="py-5"></div>
<div class="container py-5" style="min-height: 83vh">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form-night">
        <h2>Change the name of your pilot</h2>
        <%= simple_form_for @dashboard do |f| %>
          <%= f.input :name %>
          <%= f.submit 'Change name', class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="py-5"></div>
<div class="container-dashboards" style="min-height: 83vh">
  <div class="main-container">
  <%if @dashboards.empty? %>
    <h1 class='py-4'>You don't have any pilot yet</h1>
    <%= link_to '<i class="fas fa-plus"></i> Add a pilot'.html_safe, new_dashboard_path, class: "btn-flat" %>
  <%else %>
    <div class="d-inline-flex align-items-center">
      <h1 class='py-4'>Your pilots</h1>
      <%= link_to '<i class="fas fa-plus"></i> Add a pilot'.html_safe, new_dashboard_path, class: "btn-flat mx-4", style:"color: black; height:50%" %>
    </div>
    <% @dashboards.each do |dashboard| %>
      <div class="pilot-card">
        <%= link_to dashboard.name, dashboard_path(dashboard), style:"font-size: 24px" %>
        <div>
          <%= link_to edit_dashboard_path(dashboard) do%>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to dashboard_path(dashboard), method: :delete, data: {confirm: "Are you sure?"} do%>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
    <%end  %>
  </div>
</div>

app/views/dashboards/new.html.erb
<div class="py-5"></div>
<div class="container py-5" style="min-height: 83vh">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form-night">
        <h1>Add a pilot</h1>
        <%= simple_form_for @dashboard do |f| %>
          <%= f.input :name %>
          <%= f.submit 'Create Pilot', class: "btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="py-5"></div>
<% if @assets == 0 %>
  <div class="container" style="height: 80vh">
      <h1>You don't have any transaction yet...</h1>
      <div class="py-4"></div>
      <%= link_to 'Add Transaction', new_dashboard_transaction_path(@dashboard), class: "btn-flat"%>
  </div>
<% else %>
  <div class="container">
    <div class="dashboard-header">
      <%= "<h1 id='foo' class='py-4' data-dashboard-id='#{@dashboard.id}'>#{@dashboard.name}</h1>".html_safe %>
      <div>
        <%= link_to '<i class="fas fa-plus"></i> Add Transaction'.html_safe, new_dashboard_transaction_path(@dashboard), class: "btn-flat", style: "height 100%" %>
        <%= link_to 'All Transactions', dashboard_transactions_path(@dashboard), class: "btn-dark ml-3", style: "height 100%" %>
      </div>
    </div>

    <div class="d-inline-flex align-left" style="width:100%">
      <% @assets.keys.each do |key| %>
        <div class="asset-icon-card mr-2">
          <%= image_tag Asset.find_by(id_name: key).image, size: "50x50" %>
          <p style="margin:0 10px"><%= key.capitalize %></p>
        </div>
      <% end %>
    </div>


    <div id="chart" >
      <p class="loader"><i class="fas fa-cogs"></i> Computing your data...</p>
    </div>

    <div class="w-100 d-inline-flex justify-content-between">
      <div class="key-metrics-card">
        <h2 class="my-4"> <%= @dashboard.name %>'s key metrics</h2>
        <% if @total_pnl > 0 %>
          <p> Profit and Loss: <span style="color:#02C77A">+<%= @total_pnl.round(2) %> $</span></p>
        <% else %>
          <p> Profit and Loss: <span style="color:red"><%= @total_pnl.round(2) %> $</span></p>
        <% end %>
        <p>Number of assets: <%= @assets.keys.length %></p>
        <p>Total value: $<%= @dashboard.total_value(@assets).round(2) %></p>
        <p>Number of transactions: <%= @dashboard.transactions.length %></p>
      </div>
      <div class="key-metrics-card">
        <div id="pie">
          <p class="loader"><i class="fas fa-cogs"></i> Computing your data...</p>
        </div>
      </div>

    </div>


    <% @assets.keys.each do |key| %>
      <div class="asset-card asset my-4" data-asset="<%= key %>">
        <div style="width: 50%">
          <div class="my-4 d-inline-flex align-items-center">
            <%= image_tag Asset.where("id_name = '#{key}'").last.image, size: "30x30" %>
            <h2 style="margin:0 10px"><%= key.capitalize %></h2>
          </div>

          <div style="width: 45%">
            <% if @assets[key][:pnl] > 0 %>
              <p> Profit and Loss: <span style="color:#02C77A">+<%= @assets[key][:pnl].round(2) %> $</span></p>
            <% else %>
              <p> Profit and Loss: <span style="color:red"><%= @assets[key][:pnl].round(2) %> $</span></p>
            <% end %>
            <p>Value: $<%= (@assets[key][:quantity] * @assets[key][:market_price]).round(2) %></p>
            <p>Number of coins: <%= @assets[key][:quantity] %> </p>
            <p>Market price: $<%= @assets[key][:market_price].round(2) %> </p>
            <p>Average cost per coin: $<%= @assets[key][:average_cost] %></p>
            <% asset_value = @assets[key][:quantity] *  @assets[key][:market_price] %>
          </div>
        </div>
        <div class="sparkline" id="<%= key %>" style="height:250px; width: 50%" >
          <p class="loader"><i class="fas fa-cogs"></i> Computing your data...</p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>