config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/team', to: "pages#team", as: :team
  resources :notes

  resources :dashboards do
    resources :transactions, only: [:index, :edit, :update, :new, :create, :destroy]
    get '/charts/values', to: 'charts#values'
    get '/charts/pie', to: 'charts#pie'
    get '/charts/sparkline', to: 'charts#sparkline'
  end
  resources :ressources, only: [:index, :edit, :update]do
    resources :votes
  end
  get '/ressources/exchanges', to: 'ressources#exchanges', as: :exchanges
  get '/ressources/wallets', to: 'ressources#wallets', as: :wallets
  get '/ressources/youtube', to: 'ressources#youtube', as: :youtube
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @dashboard = Dashboard.find(params[:dashboard_id])
    if params[:transaction]
      @transactions = Transaction.where("date > :from AND date < :to", { from: params[:transaction][:date_from].to_date, to: params[:transaction][:date_to].to_date })
      @transactions = @transactions.where(asset_id: (params[:transaction][:asset_id]).to_i)
      @transactions = @transactions.where(dashboard_id: @dashboard.id)
    else
    @transactions = Transaction.where(dashboard_id: @dashboard.id)
    end
  end

  def new
    @transaction = Transaction.new
    @dashboard = Dashboard.find(params[:dashboard_id])
  end

  def create
    @dashboard = Dashboard.find(params[:dashboard_id])
    @transaction = Transaction.new(direction: transaction_params[:direction],
                        dashboard_id: transaction_params[:dashboard],
                        asset_id: transaction_params[:asset_id],
                        price: transaction_params[:price],
                        quantity: transaction_params[:quantity],
                        asset_name: Asset.find(transaction_params[:asset_id].to_i).name,
                        date: transaction_params[:date])
    if @transaction.save
      redirect_to dashboard_path(@dashboard)
    else
      render :new
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    @dashboard = Dashboard.find(params[:dashboard_id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.update(transaction_params)
    @dashboard = Dashboard.find(params[:dashboard_id])

    redirect_to dashboard_transactions_path(@dashboard)
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    @dashboard = Dashboard.find(params[:dashboard_id])

    redirect_to dashboard_transactions_path(@dashboard)
  end

  private

  def transaction_params
    params.require(:transaction).permit(:direction, :asset_id, :dashboard, :price, :quantity, :date)
  end
end

app/views/transactions/edit.html.erb
<div class="py-5"></div>
<div class="container py-5" style="min-height: 83vh">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4 col-xs-6">
      <div class="form-night my-4 p-6">
        <h2 class="text-center">Edit your transaction</h2>
        <%= simple_form_for [@dashboard, @transaction] do |f| %>
          <p>Asset: <abbr title="required">*</abbr></p>
          <%= f.input :asset_id, as: :select, collection:  Asset.all.map { |r| [r.name, r.id, data: { image: r.image }]}, input_html: { class: 'select2 w-100', style: "width: 100%" }, label: false %>
          <%= f.input :direction, as: :select,  collection: ["Buy", "Sell", "Add"], label: "Action"%>
          <%= f.input :price, as: :float, label: "Price in USD" %>
          <%= f.input :quantity, as: :float %>
          <p>Date<abbr title="required">*</abbr></p>
          <%= f.date_field :date, as: :date, max: Date.today, label: "date" , style: "width: 100%" %>
            <%= f.submit "Edit",   class: "btn-flat mt-4 mb-2", style: "width: 100%" %>
        <% end %>
        <%= link_to "Back", :back, class: "btn btn-dark my-2", style: "width: 100%" %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="py-5"></div>

<div class="container" style="min-height: 83vh">
  <!--<%= link_to '<i style="color: #EABF17" class="fas fa-long-arrow-alt-left"></i> Back to pilot'.html_safe, dashboard_path(@dashboard), class:"py-4", style:"color: #EABF17" %>-->
  <div class="py-2"></div>
  <div class="card search-card w-100">
    <h2 class="mb-4">Search a transaction by asset or date:</h2>
    <%= simple_form_for :transaction, url: dashboard_transactions_path, method: :get, html: { class: 'd-flex w-100 justify-content-around'} do |f| %>
        <div class="inside-form">
        <p class="ml-4 mr-2">From: <abbr title="required">*</abbr></p>
        <%= f.date_field :date_from, as: :date, :value => Date.parse("2009-01-01").to_s, class: "form-text" %>
        <p class="ml-4 mr-2">To: <abbr title="required">*</abbr></p>
        <%= f.date_field :date_to, as: :date, :value => (Date.today + 1).to_s, class: "form-text" %>
        <p class="ml-4 mr-2 ">Asset:</p>
        <%= f.input :asset_id, as: :select, collection:  Asset.all.map { |r| [r.name, r.id, data: { image: r.image }]}, input_html: { class: 'select2 w-100' }, label: false %>
        <%= f.submit 'Filter', class: "btn btn-dark ml-4" %>
      <% end %>
      </div>
  </div>
  <table class= "mt-4 table-tx">
    <thead>
      <tr>
        <th><p style="font-weight:bold">Name</p></th>
        <th><p style="font-weight:bold">Type</p></th>
        <th><p style="font-weight:bold">Quantity</p></th>
        <th><p style="font-weight:bold">Price</p></th>
        <th><p style="font-weight:bold">Date </p></th>
        <th><p style="font-weight:bold">Modifications</p></th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr class="card-transac mb-4">
          <td>
            <div class="cell-with-logo">
              <img src="<%= Asset.find(transaction.asset_id).image %>" alt="Asset icon", width="20%" height="20%">
              <p><%= Asset.find(transaction.asset_id).id_name.capitalize %></p>
            </div>
          </td>
          <td><p><%= transaction.direction %></p></td>
          <td><p><%= transaction.quantity %></p></td>
          <td><p><%= transaction.price %></p></td>
          <td><p><%= transaction.date %></p></td>
          <td>
            <%= link_to edit_dashboard_transaction_path(@dashboard, transaction) do %>
            <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to dashboard_transaction_path(@dashboard, transaction), method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
        <tr class="separator"></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="py-5"></div>
  <div class="container py-5" style="min-height: 83vh">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-4 col-xs-6">
        <div class="form-night my-4 p-6">
          <h2 class="text-center">Add a transaction</h2>
          <%= simple_form_for [@dashboard, @transaction] do |f| %>
            <p>Asset: <abbr title="required">*</abbr></p>
            <%= f.input :asset_id, as: :select, collection:  Asset.all.map { |r| [r.name, r.id, data: { image: r.image }]}, input_html: { class: 'select2 w-100', style: "width: 100%" }, label: false %>
            <%= f.input :direction, as: :select,  collection: ["Buy", "Sell", "Add"], label: "Action"%>
            <%= f.input :price, as: :float, label: "Price in USD" %>
            <%= f.input :quantity, as: :float %>
            <p>Date<abbr title="required">*</abbr></p>
            <%= f.date_field :date, as: :date, max: Date.today, label: "date" , style: "width: 100%" %>
            <%= f.hidden_field :dashboard, value: @dashboard.id %>
            <%= f.button :submit, class: 'btn-flat mt-4 mb-2', style: "width: 100%" %>
          <% end %>
          <%= link_to "Back", :back, class: "btn btn-dark my-2", style: "width: 100%" %>
        </div>
      </div>
    </div>
  </div>
</div>